NAME := $(shell basename $(PWD))
export MODULE := M1
all: $(NAME)

# # compilor
# CC := gcc
# # flags
# CFLAGS := -Wall -Wextra -g

# SRC := labyrinth.c 
# OBJ := $(SRC:.c=.o)

# # test 
# TEST_SRC := test.c
# TEST_OBJ := $(TEST_SRC:.c=.o)
# TEST_BIN := test  

# all: $(NAME)

# $(NAME): $(OBJ)
# 	$(CC) $(CFLAGS) -o $@ $^


# test: $(TEST_OBJ)
# 	$(CC) $(CFLAGS) -o $(TEST_BIN) $(TEST_OBJ)


# %.o: %.c
# 	$(CC) $(CFLAGS) -c -o $@ $<


# clean:
# 	rm -f $(OBJ) $(NAME) $(TEST_OBJ) $(TEST_BIN)

# .PHONY: all test clean


include ../.shadow/oslabs.mk
